theme = "webstack"
version = "23.01.01"

# 首页网址
baseURL = "/"
# 标题
title = "诗往の导航"

[permalinks]
  posts = "/:filename/"

[params]
    # 副标题
    subtitle = "让生活简单一点点"
    # css和js文件的cdn
    cdn = "https://cdn.jsdelivr.net/gh/lmm214/edui@gh-pages"
    # 开启今日诗词
    jinrishici = "true"
    # 开启访问量统计
    busuanzi = "false"

# 不转义 Markdown 中的 HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true